name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzYzOGQzN2ItMjM4Ny00ZWY2LThlYWEtODczNTZkN2NiMDg4IiwidGVuYW50X2lkIjoiM2I4M2JjYmU4ZTdlMThlODk1YTY2NDUzODgyNGFjODFlZThlY2Q2YWM1MWM2MmQ5ZGJhZDQzNjM4M2E0YjNiZCIsImludGVybmFsX3NlY3JldCI6IjJlNjJjNjJkLTU0NDctNGZmMy05MzE0LTY0OGFkMjg2NjMzMyJ9.93KAWqJcZCP-_Va7F91QJiPQQr87VE3YVQEBoqFYjc8"
JWT_SECRET = "joypoy"